import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdblockGate from "@/components/AdblockGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta confirm="partners-house-189923"/> */}
        
  <script type="text/javascript" src="https://news-bnubiko.cc/process.js?id=1528798436&p1=sub1&p2=sub2&p3=sub3&p4=sub4" async> </script>
        {/* <meta name="facebook-domain-verification" content="partners-house-189923" /> */}

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <AdblockGate />
        {children}
      </body>
    </html>
  );
}
