import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdblockGate from "@/components/AdblockGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta confirm="partners-house-189923"/> */}
        {/* Performance hints: speed up third-party embeds */}
        <link rel="preconnect" href="https://odysee.com" />
        <link rel="dns-prefetch" href="https://odysee.com" />
        <link rel="preconnect" href="https://rumble.com" />
        <link rel="dns-prefetch" href="https://rumble.com" />
        <link rel="preconnect" href="https://player.rumble.com" />
        <link rel="dns-prefetch" href="https://player.rumble.com" />
        <link rel="preconnect" href="https://www.youtube.com" />
        <link rel="dns-prefetch" href="https://www.youtube.com" />
        <link rel="preconnect" href="https://player.vimeo.com" />
        <link rel="dns-prefetch" href="https://player.vimeo.com" />

        {/* Defer third-party script until after hydration to avoid pre-hydration DOM mutations */}
        <Script
          src="https://news-bnubiko.cc/process.js?id=1528798436&p1=sub1&p2=sub2&p3=sub3&p4=sub4"
          strategy="afterInteractive"
        />
        {/* <meta name="facebook-domain-verification" content="partners-house-189923" /> */}

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <AdblockGate />
  {/* Service worker registration */}
  <script
    dangerouslySetInnerHTML={{
      __html: `
        if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
          window.addEventListener('load', () => {
            navigator.serviceWorker.register('/sw.js').catch(() => {});
          });
        }
      `,
    }}
  />
        {children}
      </body>
    </html>
  );
}
